export const CATEGORIES = [
  { id: "residential", icon: "assets/icons/house.svg", label: "Homes", color: "#4CAF50" },
  { id: "commercial", icon: "assets/icons/store.svg", label: "Shops", color: "#2196F3" },
  { id: "industrial", icon: "assets/icons/factory.svg", label: "Indus", color: "#FF9800" },
  { id: "parks", icon: "assets/icons/tree-pine.svg", label: "Parks", color: "#8BC34A" },
];

export const BUILDING_TYPES = {
  residential: [
    {
      id: "house",
      name: "House",
      model: "#house",
      cost: 100,
      pop: 4,
      income: 1,
      w: 1.5,
      d: 1.5,
      h: 1.2,
      tier: 1,
    },
    {
      id: "apt-small",
      name: "S.Apt",
      model: "#small-building1",
      cost: 300,
      pop: 10,
      income: 2,
      w: 1.5,
      d: 1.5,
      h: 1.8,
      tier: 1,
    },
    {
      id: "apt-med",
      name: "M.Apt",
      model: "#small-building2",
      cost: 500,
      pop: 16,
      income: 3,
      w: 2,
      d: 1.5,
      h: 2.2,
      tier: 2,
    },
    {
      id: "apt-block",
      name: "Block",
      model: "#building",
      cost: 1000,
      pop: 30,
      income: 5,
      w: 2,
      d: 2,
      h: 2.8,
      tier: 2,
    },
    {
      id: "highrise",
      name: "Mansion",
      model: "#large-building",
      cost: 3000,
      pop: 80,
      income: 12,
      w: 2,
      d: 2,
      h: 4,
      tier: 3,
    },
  ],
  commercial: [
    {
      id: "market",
      name: "Market",
      model: "#market-stall",
      cost: 150,
      income: 5,
      w: 1.2,
      d: 1.2,
      h: 1.2,
      tier: 1,
    },
    {
      id: "post-office",
      name: "Post Office",
      model: "#four-buildings",
      cost: 1000,
      income: 35,
      w: 2,
      d: 2,
      h: 2.8,
      tier: 2,
    },
    {
      id: "village-hall",
      name: "City Hall",
      model: "#city-hall",
      cost: 3500,
      income: 100,
      w: 2,
      d: 2,
      h: 4,
      tier: 3,
    },
  ],
  industrial: [
    {
      id: "workshop",
      name: "Barn",
      model: "#small-barn",
      cost: 250,
      income: 10,
      pollution: -2,
      w: 2,
      d: 1.5,
      h: 1.5,
      tier: 1,
    },
    {
      id: "factory",
      name: "Big Barn",
      model: "#big-barn",
      cost: 900,
      income: 30,
      pollution: -5,
      w: 2.5,
      d: 2,
      h: 2.2,
      tier: 2,
    },
    {
      id: "windmill",
      name: "Windmill",
      model: "#windmill",
      cost: 1200,
      income: 20,
      pollution: 0,
      w: 1.5,
      d: 1.5,
      h: 3,
      tier: 2,
    },
    {
      id: "power-plant",
      name: "Power station",
      model: "#tower-windmill",
      cost: 3000,
      income: 75,
      pollution: -15,
      w: 2,
      d: 2,
      h: 3.5,
      tier: 3,
    },
  ],
  parks: [
    {
      id: "dumpster",
      name: "Trash",
      model: "#dumpster",
      cost: 20,
      happiness: -1,
      w: 0.5,
      d: 0.5,
      h: 0.5,
      tier: 1,
    },
    {
      id: "rock",
      name: "Rocks",
      model: "#rock",
      cost: 50,
      happiness: 3,
      w: 0.8,
      d: 0.8,
      h: 0.5,
      tier: 1,
    },
  ],
};

export function getBuildingType(category, id) {
  return BUILDING_TYPES[category]?.find((t) => t.id === id);
}
